# Python stubs generated by omniidl from idl/InteractiveManage.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "Manage"
#
__name__ = "Manage"
_0_Manage = omniORB.openModule("Manage", r"idl/InteractiveManage.idl")
_0_Manage__POA = omniORB.openModule("Manage__POA", r"idl/InteractiveManage.idl")


# typedef ... StringList
class StringList:
    _NP_RepositoryId = "IDL:Manage/StringList:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_Manage.StringList = StringList
_0_Manage._d_StringList  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_Manage._ad_StringList = (omniORB.tcInternal.tv_alias, StringList._NP_RepositoryId, "StringList", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_Manage._tc_StringList = omniORB.tcInternal.createTypeCode(_0_Manage._ad_StringList)
omniORB.registerType(StringList._NP_RepositoryId, _0_Manage._ad_StringList, _0_Manage._tc_StringList)
del StringList

# interface InteractiveManage
_0_Manage._d_InteractiveManage = (omniORB.tcInternal.tv_objref, "IDL:Manage/InteractiveManage:1.0", "InteractiveManage")
omniORB.typeMapping["IDL:Manage/InteractiveManage:1.0"] = _0_Manage._d_InteractiveManage
_0_Manage.InteractiveManage = omniORB.newEmptyClass()
class InteractiveManage :
    _NP_RepositoryId = _0_Manage._d_InteractiveManage[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Manage.InteractiveManage = InteractiveManage
_0_Manage._tc_InteractiveManage = omniORB.tcInternal.createTypeCode(_0_Manage._d_InteractiveManage)
omniORB.registerType(InteractiveManage._NP_RepositoryId, _0_Manage._d_InteractiveManage, _0_Manage._tc_InteractiveManage)

# InteractiveManage operations and attributes
InteractiveManage._d_read = (((omniORB.tcInternal.tv_string,0), omniORB.typeMapping["IDL:Manage/StringList:1.0"]), (), None)

# InteractiveManage object reference
class _objref_InteractiveManage (CORBA.Object):
    _NP_RepositoryId = InteractiveManage._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def read(self, *args):
        return _omnipy.invoke(self, "read", _0_Manage.InteractiveManage._d_read, args)

    __methods__ = ["read"] + CORBA.Object.__methods__

omniORB.registerObjref(InteractiveManage._NP_RepositoryId, _objref_InteractiveManage)
_0_Manage._objref_InteractiveManage = _objref_InteractiveManage
del InteractiveManage, _objref_InteractiveManage

# InteractiveManage skeleton
__name__ = "Manage__POA"
class InteractiveManage (PortableServer.Servant):
    _NP_RepositoryId = _0_Manage.InteractiveManage._NP_RepositoryId


    _omni_op_d = {"read": _0_Manage.InteractiveManage._d_read}

InteractiveManage._omni_skeleton = InteractiveManage
_0_Manage__POA.InteractiveManage = InteractiveManage
omniORB.registerSkeleton(InteractiveManage._NP_RepositoryId, InteractiveManage)
del InteractiveManage
__name__ = "Manage"

#
# End of module "Manage"
#
__name__ = "InteractiveManage_idl"

_exported_modules = ( "Manage", )

# The end.
