# Python stubs generated by omniidl from idl/SpeechAction.idl

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA

_omnipy.checkVersion(3,0, __file__)


#
# Start of module "Action"
#
__name__ = "Action"
_0_Action = omniORB.openModule("Action", r"idl/SpeechAction.idl")
_0_Action__POA = omniORB.openModule("Action__POA", r"idl/SpeechAction.idl")


# interface SpeechAction
_0_Action._d_SpeechAction = (omniORB.tcInternal.tv_objref, "IDL:Action/SpeechAction:1.0", "SpeechAction")
omniORB.typeMapping["IDL:Action/SpeechAction:1.0"] = _0_Action._d_SpeechAction
_0_Action.SpeechAction = omniORB.newEmptyClass()
class SpeechAction :
    _NP_RepositoryId = _0_Action._d_SpeechAction[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Action.SpeechAction = SpeechAction
_0_Action._tc_SpeechAction = omniORB.tcInternal.createTypeCode(_0_Action._d_SpeechAction)
omniORB.registerType(SpeechAction._NP_RepositoryId, _0_Action._d_SpeechAction, _0_Action._tc_SpeechAction)

# SpeechAction operations and attributes
SpeechAction._d_read = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), None)

# SpeechAction object reference
class _objref_SpeechAction (CORBA.Object):
    _NP_RepositoryId = SpeechAction._NP_RepositoryId

    def __init__(self):
        CORBA.Object.__init__(self)

    def read(self, *args):
        return _omnipy.invoke(self, "read", _0_Action.SpeechAction._d_read, args)

    __methods__ = ["read"] + CORBA.Object.__methods__

omniORB.registerObjref(SpeechAction._NP_RepositoryId, _objref_SpeechAction)
_0_Action._objref_SpeechAction = _objref_SpeechAction
del SpeechAction, _objref_SpeechAction

# SpeechAction skeleton
__name__ = "Action__POA"
class SpeechAction (PortableServer.Servant):
    _NP_RepositoryId = _0_Action.SpeechAction._NP_RepositoryId


    _omni_op_d = {"read": _0_Action.SpeechAction._d_read}

SpeechAction._omni_skeleton = SpeechAction
_0_Action__POA.SpeechAction = SpeechAction
omniORB.registerSkeleton(SpeechAction._NP_RepositoryId, SpeechAction)
del SpeechAction
__name__ = "Action"

#
# End of module "Action"
#
__name__ = "SpeechAction_idl"

_exported_modules = ( "Action", )

# The end.
