# DO NOT EDIT THIS FILE!
#
# Python module RTC__POA generated by omniidl

import omniORB
omniORB.updateModule("RTC__POA")

# ** 1. Stub files contributing to this module
import SeedNoid_Mobile_idl
import BasicDataType_idl
import ExtendedDataTypes_idl

# ** 2. Sub-modules

# ** 3. End
